version: "3.7"

services:
  app:
    depends_on:
      - db
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/app
      - bundle_data:/bundle
    environment:
      S3_REGION: ap-northeast-1
      S3_ACCESS_KEY: dummy
      S3_SECRET_KEY: dummy
      S3_BUCKET: file
      S3_ENDPOINT: http://localstack:4566
      S3_ASSET_HOST: http://localhost:4566
    command: sh /scripts/command.sh
    stdin_open: true
    tty: true

  db:
    image: mysql:5.7
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=chatapp_development
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_PASSWORD=12345678
    volumes:
      - mysql_data:/var/lib/mysql

  localstack:
    image: localstack/localstack
    ports:
      - 8080:8080 # dashboard
      - 4566:4566 # edge port
    environment:
      SERVICES: s3, dynamodb
      AWS_DEFAULT_REGION: ap-northeast-1
      DATA_DIR: /tmp/localstack/data
    command: sh /scripts/setup_aws.sh
    volumes:
      - ./docker/localstack/:/docker-entrypoint-initaws.d

volumes:
  mysql_data:
  bundle_data:
